// Package kindtest is the conformance harness every channel kind must pass
// (design §5). Stage 1 ships the category-side skeleton: sample-payload
// generation and registry-wide conformance. Per-kind delivery conformance
// (delivered-or-loud-error for output kinds; explicit ErrNotAnOutputChannel
// for non-output kinds) lands with the Kind/OutputKind split in Stage 5.
package kindtest

import (
	"fmt"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"github.com/authzed/openagentprimitives/pkg/channels/channelevents"
	"github.com/authzed/openagentprimitives/pkg/channels/channelinteractions"
)

// SampleRequest builds a representative, wire-valid InteractionRequestPayload
// for a category — the payload conformance assertions and (from Stage 5) the
// per-kind delivery drivers all render this.
func SampleRequest(c channelinteractions.Category) channelevents.InteractionRequestPayload {
	audience := channelevents.InteractionAudience{
		Scope:     channelevents.AudienceRequester,
		Requester: &channelevents.ExternalIdentity{Kind: "fake", ExternalID: "U0ALICE", Email: "alice@example.com"},
	}
	if c.Deciders == channelinteractions.DecideApprovers {
		audience = channelevents.InteractionAudience{
			Scope:      channelevents.AudienceApprovers,
			Approvers:  []channelevents.ExternalIdentity{{Kind: "fake", ExternalID: "U0ALICE", Email: "alice@example.com"}},
			PublicNote: true,
		}
	}
	return channelevents.InteractionRequestPayload{
		AgentSessionRef: channelevents.SessionRef{Namespace: "default", Name: "demo-session"},
		Category:        c.Name,
		RequestRef:      "kindtest-" + c.Name,
		Lead:            fmt.Sprintf("Sample %s prompt", c.Name),
		Body:            "Generated by kindtest.SampleRequest.",
		Fields:          []channelevents.InteractionField{{Label: "Subject", Value: "demo"}},
		Excerpt:         &channelevents.InteractionExcerpt{Label: "Untrusted", Content: "```escape attempt```"},
		Actions: []channelevents.InteractionAction{
			{ID: "approve", Label: "Approve", Style: channelevents.ActionStylePrimary, Kind: channelevents.ActionKindDecision},
			{ID: "deny", Label: "Deny", Style: channelevents.ActionStyleDanger, Kind: channelevents.ActionKindDecision},
		},
		Audience: audience,
	}
}

// AssertCategoryConformance checks one category: well-formed, and its sample
// payload is wire-valid and text-renderable.
func AssertCategoryConformance(t *testing.T, c channelinteractions.Category) {
	t.Helper()
	require.NoError(t, c.Validate(), "category %q must validate", c.Name)
	req := SampleRequest(c)
	require.NoError(t, req.Validate(), "category %q sample payload must be wire-valid", c.Name)
	out := channelinteractions.RenderText(req, nil)
	assert.NotEmpty(t, out, "category %q must render on the text floor", c.Name)
	assert.Contains(t, out, req.Lead, "text floor must carry the lead")
}

// AssertRegisteredCategories runs AssertCategoryConformance over every
// category in the live registry. A new category automatically extends this
// suite — registering one that fails conformance breaks CI, not production.
func AssertRegisteredCategories(t *testing.T) {
	t.Helper()
	for _, c := range channelinteractions.All() {
		c := c
		t.Run("category_"+c.Name, func(t *testing.T) { AssertCategoryConformance(t, c) })
	}
}
