apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: spicebox-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: spicebox-operator
subjects:
  - kind: ServiceAccount
    name: spicebox-operator
    namespace: agentprimitives-system
