// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.29.3
// source: gateway.proto

package gatewayv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GatewayClient is the client API for Gateway service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GatewayClient interface {
	// Stream attaches the caller to the live exec of one streaming ToolCall and
	// pumps bytes in both directions until the tool process exits.
	//
	// The first client message MUST be Hello; anything else fails the RPC with
	// UNAUTHENTICATED. A ToolCall's exec can be attached to at most once — a
	// second Stream for the same ToolCall fails with PERMISSION_DENIED, so there
	// is no resume and no reconnect after a dropped connection.
	//
	// The server ends the RPC by sending exactly one Exit and returning. If the
	// caller disconnects first, the operator cancels the exec rather than leave
	// the sandbox process running with no consumer left to read it.
	Stream(ctx context.Context, opts ...grpc.CallOption) (Gateway_StreamClient, error)
}

type gatewayClient struct {
	cc grpc.ClientConnInterface
}

func NewGatewayClient(cc grpc.ClientConnInterface) GatewayClient {
	return &gatewayClient{cc}
}

func (c *gatewayClient) Stream(ctx context.Context, opts ...grpc.CallOption) (Gateway_StreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &Gateway_ServiceDesc.Streams[0], "/spicebox.gateway.v1.Gateway/Stream", opts...)
	if err != nil {
		return nil, err
	}
	x := &gatewayStreamClient{stream}
	return x, nil
}

type Gateway_StreamClient interface {
	Send(*Message) error
	Recv() (*Message, error)
	grpc.ClientStream
}

type gatewayStreamClient struct {
	grpc.ClientStream
}

func (x *gatewayStreamClient) Send(m *Message) error {
	return x.ClientStream.SendMsg(m)
}

func (x *gatewayStreamClient) Recv() (*Message, error) {
	m := new(Message)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// GatewayServer is the server API for Gateway service.
// All implementations must embed UnimplementedGatewayServer
// for forward compatibility
type GatewayServer interface {
	// Stream attaches the caller to the live exec of one streaming ToolCall and
	// pumps bytes in both directions until the tool process exits.
	//
	// The first client message MUST be Hello; anything else fails the RPC with
	// UNAUTHENTICATED. A ToolCall's exec can be attached to at most once — a
	// second Stream for the same ToolCall fails with PERMISSION_DENIED, so there
	// is no resume and no reconnect after a dropped connection.
	//
	// The server ends the RPC by sending exactly one Exit and returning. If the
	// caller disconnects first, the operator cancels the exec rather than leave
	// the sandbox process running with no consumer left to read it.
	Stream(Gateway_StreamServer) error
	mustEmbedUnimplementedGatewayServer()
}

// UnimplementedGatewayServer must be embedded to have forward compatible implementations.
type UnimplementedGatewayServer struct {
}

func (UnimplementedGatewayServer) Stream(Gateway_StreamServer) error {
	return status.Errorf(codes.Unimplemented, "method Stream not implemented")
}
func (UnimplementedGatewayServer) mustEmbedUnimplementedGatewayServer() {}

// UnsafeGatewayServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GatewayServer will
// result in compilation errors.
type UnsafeGatewayServer interface {
	mustEmbedUnimplementedGatewayServer()
}

func RegisterGatewayServer(s grpc.ServiceRegistrar, srv GatewayServer) {
	s.RegisterService(&Gateway_ServiceDesc, srv)
}

func _Gateway_Stream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GatewayServer).Stream(&gatewayStreamServer{stream})
}

type Gateway_StreamServer interface {
	Send(*Message) error
	Recv() (*Message, error)
	grpc.ServerStream
}

type gatewayStreamServer struct {
	grpc.ServerStream
}

func (x *gatewayStreamServer) Send(m *Message) error {
	return x.ServerStream.SendMsg(m)
}

func (x *gatewayStreamServer) Recv() (*Message, error) {
	m := new(Message)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Gateway_ServiceDesc is the grpc.ServiceDesc for Gateway service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Gateway_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "spicebox.gateway.v1.Gateway",
	HandlerType: (*GatewayServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Stream",
			Handler:       _Gateway_Stream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "gateway.proto",
}
