package authz

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Permission) DeepCopyInto(out *Permission) {
	*out = *in
	if in.Check != nil {
		in, out := &in.Check, &out.Check
		*out = new(PermissionCheck)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Permission.
func (in *Permission) DeepCopy() *Permission {
	if in == nil {
		return nil
	}
	out := new(Permission)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PermissionCheck) DeepCopyInto(out *PermissionCheck) {
	*out = *in
	if in.ResourceIDTransforms != nil {
		in, out := &in.ResourceIDTransforms, &out.ResourceIDTransforms
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.GrantBindsArgs != nil {
		in, out := &in.GrantBindsArgs, &out.GrantBindsArgs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PermissionCheck.
func (in *PermissionCheck) DeepCopy() *PermissionCheck {
	if in == nil {
		return nil
	}
	out := new(PermissionCheck)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PermissionVariant) DeepCopyInto(out *PermissionVariant) {
	*out = *in
	in.Check.DeepCopyInto(&out.Check)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PermissionVariant.
func (in *PermissionVariant) DeepCopy() *PermissionVariant {
	if in == nil {
		return nil
	}
	out := new(PermissionVariant)
	in.DeepCopyInto(out)
	return out
}
