package provider_test

import (
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"github.com/authzed/openagentprimitives/pkg/platform/identity/provider"
)

// providerIDs projects the matched shapes to their catalog ids. Nil in, nil out,
// so "matched nothing" stays distinguishable from an empty-but-allocated slice.
func providerIDs(ms []provider.TokenShapeMatch) []string {
	if len(ms) == 0 {
		return nil
	}
	out := make([]string, 0, len(ms))
	for _, m := range ms {
		out = append(out, m.ProviderID)
	}
	return out
}

// TestValidateToken_NamesTheShapeTheValueActuallyHas covers the half of a
// rejection that turns "this is wrong" into "you pasted the other one". The
// expected shape alone is not enough when two credentials share a prefix, are
// generated by the same vendor, and back sibling toolkits.
func TestValidateToken_NamesTheShapeTheValueActuallyHas(t *testing.T) {
	apiKey, ok := provider.ByID("anthropic-api-key")
	require.True(t, ok, "anthropic-api-key provider must be embedded")
	oauth, ok := provider.ByID("anthropic-oauth")
	require.True(t, ok, "anthropic-oauth provider must be embedded")

	cases := []struct {
		name        string
		prov        provider.Provider
		token       string
		wantMatches []string
		// wantMsgContains are substrings the rendered error must carry.
		wantMsgContains []string
	}{
		{
			name:            "subscription token in the API-key credential: names anthropic-oauth and both shapes",
			prov:            *apiKey,
			token:           "sk-ant-oat01-demo-value",
			wantMatches:     []string{"anthropic-oauth"},
			wantMsgContains: []string{"anthropic-api-key", "sk-ant-api", "anthropic-oauth", "sk-ant-oat"},
		},
		{
			name:            "API key in the subscription credential: the exact mirror",
			prov:            *oauth,
			token:           "sk-ant-api03-demo-value",
			wantMatches:     []string{"anthropic-api-key"},
			wantMsgContains: []string{"anthropic-oauth", "sk-ant-oat", "anthropic-api-key", "sk-ant-api"},
		},
		{
			name:            "value matching no declared shape: rejected with no misleading suggestion",
			prov:            *apiKey,
			token:           "demo-value-matching-nothing",
			wantMatches:     nil,
			wantMsgContains: []string{"anthropic-api-key", "sk-ant-api"},
		},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			err := provider.ValidateToken(tc.prov, tc.token)
			require.Error(t, err, "the token must be rejected for this case")

			var fe *provider.TokenFormatError
			require.ErrorAs(t, err, &fe)
			assert.Equal(t, tc.wantMatches, providerIDs(fe.Matches))
			assert.NotContains(t, providerIDs(fe.Matches), tc.prov.ID,
				"the rejecting provider can never be among the shapes the value matches")
			for _, want := range tc.wantMsgContains {
				assert.Contains(t, err.Error(), want)
			}
			assert.NotContains(t, err.Error(), tc.token,
				"a rejection must never echo the value back")
		})
	}
}
