apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - authzd
  - crds
  - extractord
  - identities
  - manager
  - networkpolicy
  - spicedb-operator
  - toolchains
  - webd
  - workspace-provisioner
